---
- name: Converge
  hosts: all
  #become: true

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_facts.os_family == 'Debian'
      changed_when: false

    - name: Install test dependencies (Debian).
      package:
        name: netcat-traditional
        state: present
      when: ansible_facts.os_family == 'Debian'

    - name: Install test dependencies (RedHat).
      package:
        name: nc
        state: present
      when: ansible_facts.os_family == 'RedHat'

  roles:
    - role: geerlingguy.munin-node
